[metrics]
go_process = true

[api]
address = ":5002"

[postgres]
dsn = "postgres://postgres:postgres@127.0.0.1:5433/chain_data"

[jetstream]
endpoint = "nats://127.0.0.1:4222"
id = "eth-indexer-1"

[chain]
rpc_endpoint = "http://localhost:8545"
chainid = 1337
